### ISSUE TITLE
Nip-05 verification not happening because kind 0 is rejected?

### ISSUE THREAD

**Issue by Sjors** [scsibug/nostr-rs-relay#211]
I have:

```toml
[verified_users]
mode = "enabled"
domain_whitelist = ["f.sprovoost.nl"]
```

When I try to send nodes to the relay (using Mostr) they're initially rejected as unauthorised. That makes sense, because the relay wouldn't know where to look up the pubkey.

But when I manually trigger a kind 0 event (by changing a bio), that event itself is rejected.

This seems like a chicken egg problem?
